language: python
dist: xenial
sudo: required
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - gdb

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: "3.7"
      install:
        - pip install -U pip setuptools flake8
      script:
        - flake8

install:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - pip install -U pip setuptools tox tox-travis

script:
  - tox
