language: python
cache: pip
python:
  # - "2.7"
  # - "3.4"
  # - "3.5-dev"
  # 3.6 is tested via coverage
  - "3.7-dev"
env:
  - TARGET=ci-test

before_install:
  - export TRAVIS_PYTHON_PATH=`which python`
    # Travis comes with an ancient version of pytest preinstalled globally,
    # which breaks automatic dependency checks for setup.py. Force upgrade.
  - $TRAVIS_PYTHON_PATH -m pip install --upgrade pip
  - $TRAVIS_PYTHON_PATH -m pip install --upgrade pytest

install:
  - make depends PYTHON=$TRAVIS_PYTHON_PATH

script:
  #- make $TARGET PYTHON=python$TRAVIS_PYTHON_VERSION
  - make $TARGET PYTHON=$TRAVIS_PYTHON_PATH

